package e.dominio.entity;
import java.util.HashSet;
import java.util.Set;

import e.base.dominio.DominioBaseNombre;

/**
 * Clientes generated by hbm2java
 */
public class Clientes extends DominioBaseNombre {

	private Integer idClientes;
	private Empresa empresa;
	private String nombre;
	private String apellido;
	private String celular;
	private String telefono;
	private String email;
	private String domicilio;
	private String colegio;
	private Set encargoses = new HashSet(0);
	private Set medidases = new HashSet(0);
	private Set modeloses = new HashSet(0);
	private Set fechapruebas = new HashSet(0);

	public Clientes() {
	}

	public Clientes(Empresa empresa, String nombre, String apellido, String celular, String telefono, String email, String domicilio, String colegio, Set encargoses, Set medidases, Set modeloses,
			Set fechapruebas) {
		this.empresa = empresa;
		this.nombre = nombre;
		this.apellido = apellido;
		this.celular = celular;
		this.telefono = telefono;
		this.email = email;
		this.domicilio = domicilio;
		this.colegio = colegio;
		this.encargoses = encargoses;
		this.medidases = medidases;
		this.modeloses = modeloses;
		this.fechapruebas = fechapruebas;
	}

	public Integer getIdClientes() {
		return this.idClientes;
	}

	public void setIdClientes(Integer idClientes) {
		this.idClientes = idClientes;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getColegio() {
		return this.colegio;
	}

	public void setColegio(String colegio) {
		this.colegio = colegio;
	}

	public Set getEncargoses() {
		return this.encargoses;
	}

	public void setEncargoses(Set encargoses) {
		this.encargoses = encargoses;
	}

	public Set getMedidases() {
		return this.medidases;
	}

	public void setMedidases(Set medidases) {
		this.medidases = medidases;
	}

	public Set getModeloses() {
		return this.modeloses;
	}

	public void setModeloses(Set modeloses) {
		this.modeloses = modeloses;
	}

	public Set getFechapruebas() {
		return this.fechapruebas;
	}

	public void setFechapruebas(Set fechapruebas) {
		this.fechapruebas = fechapruebas;
	}

}
