package e.dominio.entity;
// Generated 26/12/2016 09:56:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private Integer idEmpresa;
	private String nombreEmpresa;
	private String domicilio;
	private String telefono;
	private String email;
	private Set usuarios = new HashSet(0);
	private Set clienteses = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String nombreEmpresa, String domicilio, String telefono, String email, Set usuarios, Set clienteses) {
		this.nombreEmpresa = nombreEmpresa;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.email = email;
		this.usuarios = usuarios;
		this.clienteses = clienteses;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set clienteses) {
		this.clienteses = clienteses;
	}

}
