package e.dominio.entity;
// default package
// Generated 26/12/2016 09:56:18 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Fechaprueba generated by hbm2java
 */
public class Fechaprueba implements java.io.Serializable {

	private Integer idFechaPrueba;
	private Clientes clientes;
	private Date fechaPrueba;

	public Fechaprueba() {
	}

	public Fechaprueba(Clientes clientes) {
		this.clientes = clientes;
	}

	public Fechaprueba(Clientes clientes, Date fechaPrueba) {
		this.clientes = clientes;
		this.fechaPrueba = fechaPrueba;
	}

	public Integer getIdFechaPrueba() {
		return this.idFechaPrueba;
	}

	public void setIdFechaPrueba(Integer idFechaPrueba) {
		this.idFechaPrueba = idFechaPrueba;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFechaPrueba() {
		return this.fechaPrueba;
	}

	public void setFechaPrueba(Date fechaPrueba) {
		this.fechaPrueba = fechaPrueba;
	}

}
