package e.dominio.entity;

// Generated 28/10/2016 11:29:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import e.base.dominio.DominioBaseNombre;

/**
 * Medidas generated by hbm2java
 */
@Entity
@Table(name = "medidas", catalog = "nicolejeniffer")
public class Medidas extends DominioBaseNombre {

	private int idMedidas;
	private Clientes clientes;
	private BigDecimal largoPolera;
	private BigDecimal largoCorset;
	private BigDecimal espalda;
	private BigDecimal contornoBusto;
	private BigDecimal contornoCadera;
	private BigDecimal costado;
	private BigDecimal cintura;
	private BigDecimal cadera;
	private BigDecimal talleEspalda;
	private BigDecimal talleDelantero;
	private BigDecimal sisa;
	private BigDecimal largoManga;
	private BigDecimal largoPollera;
	private String observaciones;
	private Date fechaMedida;
	private BigDecimal busto;
	private BigDecimal bajoBusto;
	private BigDecimal anteCadera;
	private BigDecimal picoBusto1;
	private BigDecimal picoBusto2;

	public Medidas() {
	}

	public Medidas(int idMedidas) {
		this.idMedidas = idMedidas;
	}

	public Medidas(int idMedidas, Clientes clientes, BigDecimal largoPolera,
			BigDecimal largoCorset, BigDecimal espalda,
			BigDecimal contornoBusto, BigDecimal contornoCadera,
			BigDecimal costado, BigDecimal cintura, BigDecimal cadera,
			BigDecimal talleEspalda, BigDecimal talleDelantero,
			BigDecimal sisa, BigDecimal largoManga, BigDecimal largoPollera,
			String observaciones, Date fechaMedida, BigDecimal busto, BigDecimal bajoBusto,
			BigDecimal anteCadera, BigDecimal picoBusto1, BigDecimal picoBusto2) {
		this.idMedidas = idMedidas;
		this.clientes = clientes;
		this.largoPolera = largoPolera;
		this.largoCorset = largoCorset;
		this.espalda = espalda;
		this.contornoBusto = contornoBusto;
		this.contornoCadera = contornoCadera;
		this.costado = costado;
		this.cintura = cintura;
		this.cadera = cadera;
		this.talleEspalda = talleEspalda;
		this.talleDelantero = talleDelantero;
		this.sisa = sisa;
		this.largoManga = largoManga;
		this.largoPollera = largoPollera;
		this.observaciones = observaciones;
		this.fechaMedida = fechaMedida;
		this.busto = busto;
		this.bajoBusto = bajoBusto;
		this.anteCadera = anteCadera;
		this.picoBusto1 = picoBusto1;
		this.picoBusto2 = picoBusto2;
	}

	@Id
	@Column(name = "idMedidas", unique = true, nullable = false)
	public int getIdMedidas() {
		return this.idMedidas;
	}

	public void setIdMedidas(int idMedidas) {
		this.idMedidas = idMedidas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Clientes_idClientes")
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "LargoPolera", precision = 10, scale = 4)
	public BigDecimal getLargoPolera() {
		return this.largoPolera;
	}

	public void setLargoPolera(BigDecimal largoPolera) {
		this.largoPolera = largoPolera;
	}

	@Column(name = "LargoCorset", precision = 10, scale = 4)
	public BigDecimal getLargoCorset() {
		return this.largoCorset;
	}

	public void setLargoCorset(BigDecimal largoCorset) {
		this.largoCorset = largoCorset;
	}

	@Column(name = "Espalda", precision = 10, scale = 4)
	public BigDecimal getEspalda() {
		return this.espalda;
	}

	public void setEspalda(BigDecimal espalda) {
		this.espalda = espalda;
	}

	@Column(name = "ContornoBusto", precision = 10, scale = 4)
	public BigDecimal getContornoBusto() {
		return this.contornoBusto;
	}

	public void setContornoBusto(BigDecimal contornoBusto) {
		this.contornoBusto = contornoBusto;
	}

	@Column(name = "ContornoCadera", precision = 10, scale = 4)
	public BigDecimal getContornoCadera() {
		return this.contornoCadera;
	}

	public void setContornoCadera(BigDecimal contornoCadera) {
		this.contornoCadera = contornoCadera;
	}

	@Column(name = "Costado", precision = 10, scale = 4)
	public BigDecimal getCostado() {
		return this.costado;
	}

	public void setCostado(BigDecimal costado) {
		this.costado = costado;
	}

	@Column(name = "Cintura", precision = 10, scale = 4)
	public BigDecimal getCintura() {
		return this.cintura;
	}

	public void setCintura(BigDecimal cintura) {
		this.cintura = cintura;
	}

	@Column(name = "Cadera", precision = 10, scale = 4)
	public BigDecimal getCadera() {
		return this.cadera;
	}

	public void setCadera(BigDecimal cadera) {
		this.cadera = cadera;
	}

	@Column(name = "TalleEspalda", precision = 10, scale = 4)
	public BigDecimal getTalleEspalda() {
		return this.talleEspalda;
	}

	public void setTalleEspalda(BigDecimal talleEspalda) {
		this.talleEspalda = talleEspalda;
	}

	@Column(name = "TalleDelantero", precision = 10, scale = 4)
	public BigDecimal getTalleDelantero() {
		return this.talleDelantero;
	}

	public void setTalleDelantero(BigDecimal talleDelantero) {
		this.talleDelantero = talleDelantero;
	}

	@Column(name = "Sisa", precision = 10, scale = 4)
	public BigDecimal getSisa() {
		return this.sisa;
	}

	public void setSisa(BigDecimal sisa) {
		this.sisa = sisa;
	}

	@Column(name = "LargoManga", precision = 10, scale = 4)
	public BigDecimal getLargoManga() {
		return this.largoManga;
	}

	public void setLargoManga(BigDecimal largoManga) {
		this.largoManga = largoManga;
	}

	@Column(name = "LargoPollera", precision = 10, scale = 4)
	public BigDecimal getLargoPollera() {
		return this.largoPollera;
	}

	public void setLargoPollera(BigDecimal largoPollera) {
		this.largoPollera = largoPollera;
	}

	@Column(name = "Observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaMedida", length = 10)
	public Date getFechaMedida() {
		return this.fechaMedida;
	}

	public void setFechaMedida(Date fechaMedida) {
		this.fechaMedida = fechaMedida;
	}
	
	public BigDecimal getBusto() {
		return busto;
	}

	public void setBusto(BigDecimal busto) {
		this.busto = busto;
	}

	public BigDecimal getBajoBusto() {
		return bajoBusto;
	}

	public void setBajoBusto(BigDecimal bajoBusto) {
		this.bajoBusto = bajoBusto;
	}

	public BigDecimal getAnteCadera() {
		return anteCadera;
	}

	public void setAnteCadera(BigDecimal anteCadera) {
		this.anteCadera = anteCadera;
	}

	public BigDecimal getPicoBusto1() {
		return picoBusto1;
	}

	public void setPicoBusto1(BigDecimal picoBusto1) {
		this.picoBusto1 = picoBusto1;
	}

	public BigDecimal getPicoBusto2() {
		return picoBusto2;
	}

	public void setPicoBusto2(BigDecimal picoBusto2) {
		this.picoBusto2 = picoBusto2;
	}
}
