package e.dominio.entity;
// default package
// Generated 26/12/2016 09:56:18 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import e.base.dominio.DominioBaseNombre;

/**
 * Medidas generated by hbm2java
 */
public class Medidas extends DominioBaseNombre {

	private Integer idMedidas;
	private Clientes clientes;
	private BigDecimal largoPolera;
	private BigDecimal largoCorset;
	private BigDecimal espalda;
	private BigDecimal contornoBusto;
	private BigDecimal contornoCadera;
	private BigDecimal costado;
	private BigDecimal cintura;
	private BigDecimal cadera;
	private BigDecimal talleEspalda;
	private BigDecimal talleDelantero;
	private BigDecimal sisa;
	private BigDecimal largoManga;
	private BigDecimal largoPollera;
	private String observaciones;
	private Date fechaMedida;
	private BigDecimal busto;
	private BigDecimal bajoBusto;
	private BigDecimal anteCadera;
	private BigDecimal picoBusto1;
	private BigDecimal picoBusto2;

	public Medidas() {
	}

	public Medidas(Clientes clientes, BigDecimal largoPolera, BigDecimal largoCorset, BigDecimal espalda, BigDecimal contornoBusto, BigDecimal contornoCadera, BigDecimal costado, BigDecimal cintura,
			BigDecimal cadera, BigDecimal talleEspalda, BigDecimal talleDelantero, BigDecimal sisa, BigDecimal largoManga, BigDecimal largoPollera, String observaciones, Date fechaMedida,
			BigDecimal busto, BigDecimal bajoBusto, BigDecimal anteCadera, BigDecimal picoBusto1, BigDecimal picoBusto2) {
		this.clientes = clientes;
		this.largoPolera = largoPolera;
		this.largoCorset = largoCorset;
		this.espalda = espalda;
		this.contornoBusto = contornoBusto;
		this.contornoCadera = contornoCadera;
		this.costado = costado;
		this.cintura = cintura;
		this.cadera = cadera;
		this.talleEspalda = talleEspalda;
		this.talleDelantero = talleDelantero;
		this.sisa = sisa;
		this.largoManga = largoManga;
		this.largoPollera = largoPollera;
		this.observaciones = observaciones;
		this.fechaMedida = fechaMedida;
		this.busto = busto;
		this.bajoBusto = bajoBusto;
		this.anteCadera = anteCadera;
		this.picoBusto1 = picoBusto1;
		this.picoBusto2 = picoBusto2;
	}

	public Integer getIdMedidas() {
		return this.idMedidas;
	}

	public void setIdMedidas(Integer idMedidas) {
		this.idMedidas = idMedidas;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public BigDecimal getLargoPolera() {
		return this.largoPolera;
	}

	public void setLargoPolera(BigDecimal largoPolera) {
		this.largoPolera = largoPolera;
	}

	public BigDecimal getLargoCorset() {
		return this.largoCorset;
	}

	public void setLargoCorset(BigDecimal largoCorset) {
		this.largoCorset = largoCorset;
	}

	public BigDecimal getEspalda() {
		return this.espalda;
	}

	public void setEspalda(BigDecimal espalda) {
		this.espalda = espalda;
	}

	public BigDecimal getContornoBusto() {
		return this.contornoBusto;
	}

	public void setContornoBusto(BigDecimal contornoBusto) {
		this.contornoBusto = contornoBusto;
	}

	public BigDecimal getContornoCadera() {
		return this.contornoCadera;
	}

	public void setContornoCadera(BigDecimal contornoCadera) {
		this.contornoCadera = contornoCadera;
	}

	public BigDecimal getCostado() {
		return this.costado;
	}

	public void setCostado(BigDecimal costado) {
		this.costado = costado;
	}

	public BigDecimal getCintura() {
		return this.cintura;
	}

	public void setCintura(BigDecimal cintura) {
		this.cintura = cintura;
	}

	public BigDecimal getCadera() {
		return this.cadera;
	}

	public void setCadera(BigDecimal cadera) {
		this.cadera = cadera;
	}

	public BigDecimal getTalleEspalda() {
		return this.talleEspalda;
	}

	public void setTalleEspalda(BigDecimal talleEspalda) {
		this.talleEspalda = talleEspalda;
	}

	public BigDecimal getTalleDelantero() {
		return this.talleDelantero;
	}

	public void setTalleDelantero(BigDecimal talleDelantero) {
		this.talleDelantero = talleDelantero;
	}

	public BigDecimal getSisa() {
		return this.sisa;
	}

	public void setSisa(BigDecimal sisa) {
		this.sisa = sisa;
	}

	public BigDecimal getLargoManga() {
		return this.largoManga;
	}

	public void setLargoManga(BigDecimal largoManga) {
		this.largoManga = largoManga;
	}

	public BigDecimal getLargoPollera() {
		return this.largoPollera;
	}

	public void setLargoPollera(BigDecimal largoPollera) {
		this.largoPollera = largoPollera;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFechaMedida() {
		return this.fechaMedida;
	}

	public void setFechaMedida(Date fechaMedida) {
		this.fechaMedida = fechaMedida;
	}

	public BigDecimal getBusto() {
		return this.busto;
	}

	public void setBusto(BigDecimal busto) {
		this.busto = busto;
	}

	public BigDecimal getBajoBusto() {
		return this.bajoBusto;
	}

	public void setBajoBusto(BigDecimal bajoBusto) {
		this.bajoBusto = bajoBusto;
	}

	public BigDecimal getAnteCadera() {
		return this.anteCadera;
	}

	public void setAnteCadera(BigDecimal anteCadera) {
		this.anteCadera = anteCadera;
	}

	public BigDecimal getPicoBusto1() {
		return this.picoBusto1;
	}

	public void setPicoBusto1(BigDecimal picoBusto1) {
		this.picoBusto1 = picoBusto1;
	}

	public BigDecimal getPicoBusto2() {
		return this.picoBusto2;
	}

	public void setPicoBusto2(BigDecimal picoBusto2) {
		this.picoBusto2 = picoBusto2;
	}

}
