package e.dominio.entity;

// Generated 01-oct-2015 15:21:07 by Hibernate Tools 3.4.0.CR1

/**
 * ModelosId generated by hbm2java
 */
public class ModelosId implements java.io.Serializable {

	private int idModelos;
	private int clientesIdClientes;

	public ModelosId() {
	}

	public ModelosId(int idModelos, int clientesIdClientes) {
		this.idModelos = idModelos;
		this.clientesIdClientes = clientesIdClientes;
	}

	public int getIdModelos() {
		return this.idModelos;
	}

	public void setIdModelos(int idModelos) {
		this.idModelos = idModelos;
	}

	public int getClientesIdClientes() {
		return this.clientesIdClientes;
	}

	public void setClientesIdClientes(int clientesIdClientes) {
		this.clientesIdClientes = clientesIdClientes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelosId))
			return false;
		ModelosId castOther = (ModelosId) other;

		return (this.getIdModelos() == castOther.getIdModelos())
				&& (this.getClientesIdClientes() == castOther
						.getClientesIdClientes());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdModelos();
		result = 37 * result + this.getClientesIdClientes();
		return result;
	}

}
