package e.dominio.entity;

// Generated 01-oct-2015 15:21:07 by Hibernate Tools 3.4.0.CR1

/**
 * Modelos generated by hbm2java
 */
public class Modelos implements java.io.Serializable {

	private ModelosId id;
	private Clientes clientes;
	private byte[] imagen;
	private String nombreModelo;
	private String observacion;
	private String colorVestido;

	public Modelos() {
	}

	public Modelos(ModelosId id, Clientes clientes) {
		this.id = id;
		this.clientes = clientes;
	}

	public Modelos(ModelosId id, Clientes clientes, byte[] imagen,
			String nombreModelo, String observacion, String colorVestido) {
		this.id = id;
		this.clientes = clientes;
		this.imagen = imagen;
		this.nombreModelo = nombreModelo;
		this.observacion = observacion;
		this.colorVestido = colorVestido;
	}

	public ModelosId getId() {
		return this.id;
	}

	public void setId(ModelosId id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public String getNombreModelo() {
		return this.nombreModelo;
	}

	public void setNombreModelo(String nombreModelo) {
		this.nombreModelo = nombreModelo;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getColorVestido() {
		return this.colorVestido;
	}

	public void setColorVestido(String colorVestido) {
		this.colorVestido = colorVestido;
	}

}
