package e.dominio.entity;

// Generated 28/10/2016 11:29:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import e.base.dominio.DominioBaseNombre;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "pagos", catalog = "nicolejeniffer")
public class Pagos extends DominioBaseNombre {

	private int idPagos;
	private Encargos encargos;
	private Date fechaPago;
	private BigDecimal importe;
	private Integer cantidad;
	private String detalle;
	private BigDecimal precioUnitario;
	private BigDecimal precioTotal;

	public Pagos() {
	}

	public Pagos(int idPagos) {
		this.idPagos = idPagos;
	}

	public Pagos(int idPagos, Encargos encargos, Date fechaPago,
			BigDecimal importe, Integer cantidad, String detalle,
			BigDecimal precioUnitario, BigDecimal precioTotal) {
		this.idPagos = idPagos;
		this.encargos = encargos;
		this.fechaPago = fechaPago;
		this.importe = importe;
		this.cantidad = cantidad;
		this.detalle = detalle;
		this.precioUnitario = precioUnitario;
		this.precioTotal = precioTotal;
	}

	@Id
	@Column(name = "idPagos", unique = true, nullable = false)
	public int getIdPagos() {
		return this.idPagos;
	}

	public void setIdPagos(int idPagos) {
		this.idPagos = idPagos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Encargos_idEncargo")
	public Encargos getEncargos() {
		return this.encargos;
	}

	public void setEncargos(Encargos encargos) {
		this.encargos = encargos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaPago", length = 10)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "Importe", precision = 10, scale = 4)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "Cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Detalle", length = 45)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "PrecioUnitario", precision = 10, scale = 4)
	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "PrecioTotal", precision = 10, scale = 4)
	public BigDecimal getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(BigDecimal precioTotal) {
		this.precioTotal = precioTotal;
	}

}
