package e.dominio.entity;

// Generated 01-oct-2015 15:21:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos implements java.io.Serializable {

	private int idPagos;
	private Date fechaPago;
	private BigDecimal importe;
	private Integer cantidad;
	private String detalle;
	private BigDecimal precioUnitario;
	private BigDecimal precioTotal;

	public Pagos() {
	}

	public Pagos(int idPagos) {
		this.idPagos = idPagos;
	}

	public Pagos(int idPagos, Date fechaPago, BigDecimal importe,
			Integer cantidad, String detalle, BigDecimal precioUnitario,
			BigDecimal precioTotal) {
		this.idPagos = idPagos;
		this.fechaPago = fechaPago;
		this.importe = importe;
		this.cantidad = cantidad;
		this.detalle = detalle;
		this.precioUnitario = precioUnitario;
		this.precioTotal = precioTotal;
	}

	public int getIdPagos() {
		return this.idPagos;
	}

	public void setIdPagos(int idPagos) {
		this.idPagos = idPagos;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public BigDecimal getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(BigDecimal precioTotal) {
		this.precioTotal = precioTotal;
	}

}
