package e.dominio.entity;

// Generated 28/10/2016 11:29:40 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import e.base.dominio.DominioBaseNombre;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "nicolejeniffer")
public class Rol extends DominioBaseNombre {

	private Integer idRol;
	private String descripcion;
	private Set usuariorols = new HashSet(0);

	public Rol() {
	}

	public Rol(String descripcion, Set usuariorols) {
		this.descripcion = descripcion;
		this.usuariorols = usuariorols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRol", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "Descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set getUsuariorols() {
		return this.usuariorols;
	}

	public void setUsuariorols(Set usuariorols) {
		this.usuariorols = usuariorols;
	}

}
