package e.dominio.entity;
// default package
// Generated 26/12/2016 09:56:18 by Hibernate Tools 4.0.0

/**
 * Usuariorol generated by hbm2java
 */
public class Usuariorol implements java.io.Serializable {

	private Integer idUsuarioRol;
	private Rol rol;
	private Usuario usuario;

	public Usuariorol() {
	}

	public Usuariorol(Rol rol, Usuario usuario) {
		this.rol = rol;
		this.usuario = usuario;
	}

	public Integer getIdUsuarioRol() {
		return this.idUsuarioRol;
	}

	public void setIdUsuarioRol(Integer idUsuarioRol) {
		this.idUsuarioRol = idUsuarioRol;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
