package e.dominio.entity;

// Generated 28/10/2016 11:29:40 by Hibernate Tools 4.0.0

import e.base.dominio.DominioBaseNombre;

/**
 * Usuariorol generated by hbm2java
 */
public class Usuariorol extends DominioBaseNombre {

	private Integer idUsuarioRol;
	private Rol rol;
	private Usuario usuario;

	public Usuariorol() {
	}

	public Usuariorol(Rol rol, Usuario usuario) {
		this.rol = rol;
		this.usuario = usuario;
	}

	public Integer getIdUsuarioRol() {
		return this.idUsuarioRol;
	}

	public void setIdUsuarioRol(Integer idUsuarioRol) {
		this.idUsuarioRol = idUsuarioRol;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
