package e.dominio.entity;
// default package
// Generated 26/12/2016 09:56:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Valordominio generated by hbm2java
 */
public class Valordominio implements java.io.Serializable {

	private Integer idValorDominio;
	private String descripcion;
	private Set encargoses = new HashSet(0);

	public Valordominio() {
	}

	public Valordominio(String descripcion, Set encargoses) {
		this.descripcion = descripcion;
		this.encargoses = encargoses;
	}

	public Integer getIdValorDominio() {
		return this.idValorDominio;
	}

	public void setIdValorDominio(Integer idValorDominio) {
		this.idValorDominio = idValorDominio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getEncargoses() {
		return this.encargoses;
	}

	public void setEncargoses(Set encargoses) {
		this.encargoses = encargoses;
	}

}
